server:
  port: 8080
  servlet:
    context-path: /appDemo
  tomcat:
    threads:
      min-spare: 20       # thread minimum idle
      max: 200            # maksimum worker thread
    accept-count: 100     # queue saat semua thread sibuk
    max-connections: 10000
  connection-timeout: 5s  # waktu tunggu koneksi masuk

spring:
  profiles:
    active: prod

  datasource:
    url: "jdbc:oracle:thin:@192.168.50.6:1521:otmpf"
    username: hrd_mepro
    password: hrd_meprofarm1
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MyHikariPool

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.OracleDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.mepro.democrud: DEBUG 
    org.hibernate.SQL: DEBUG
    org.hibernate.transaction: TRACE
  file:
    name: logs/app-prod.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
      total-size-cap: 100MB

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: when-authorized

# Optional: jika pakai actuator & ingin secure monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
